// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn7pLx8i291scX3GMce40AwpXOheXmO5o',
    appId: '1:940035140831:web:c416016be19f2b54bccd6a',
    messagingSenderId: '940035140831',
    projectId: 'captain-app-22b7e',
    authDomain: 'captain-app-22b7e.firebaseapp.com',
    storageBucket: 'captain-app-22b7e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ5Hlg6db9AjZ5CxTP21KW9S39aIGrc68',
    appId: '1:940035140831:android:7675cdef34183465bccd6a',
    messagingSenderId: '940035140831',
    projectId: 'captain-app-22b7e',
    storageBucket: 'captain-app-22b7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDevNLT6QYTPAt5elvG0T4cN18iH5GUuq8',
    appId: '1:940035140831:ios:97037c2611492c2ebccd6a',
    messagingSenderId: '940035140831',
    projectId: 'captain-app-22b7e',
    storageBucket: 'captain-app-22b7e.firebasestorage.app',
    iosBundleId: 'com.example.captainApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDevNLT6QYTPAt5elvG0T4cN18iH5GUuq8',
    appId: '1:940035140831:ios:97037c2611492c2ebccd6a',
    messagingSenderId: '940035140831',
    projectId: 'captain-app-22b7e',
    storageBucket: 'captain-app-22b7e.firebasestorage.app',
    iosBundleId: 'com.example.captainApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn7pLx8i291scX3GMce40AwpXOheXmO5o',
    appId: '1:940035140831:web:7a66f0e3fb7e5a73bccd6a',
    messagingSenderId: '940035140831',
    projectId: 'captain-app-22b7e',
    authDomain: 'captain-app-22b7e.firebaseapp.com',
    storageBucket: 'captain-app-22b7e.firebasestorage.app',
  );
}
